Lesson 7
MaciekBella/invoicing-system-maciek-bella pull request #10
Opened 2022-12-29 15:30 UTC by MaciekBella

Task 5
Task 5

2022-12-29 15:46 UTC, BartoszKamyszek reviewed
Uruchamiałeś aplikacje lokalnie z tymi profilami?

2022-12-29 16:34 UTC, BartoszKamyszek requested changes
usuń tez plik application.properties, bo jest duplikacją yamla. Wartości ścieżek do plików tez nie są używane, użyj @Value. Jak już uruchomisz aplikacje w profilu dev to zobacz jaki błąd Ci leci, podpowiedź w Springu beany nie mogą być definiowane w kilku miejscach :)

2022-12-29 16:34 UTC, BartoszKamyszek commented on app/src/main/resources/application.yml
> +        invoicing.db: DEBUG
w pliku yaml wcięcia mają znaczenie, te konfigi nie powinny mieć tego wcięcia

2022-12-29 16:34 UTC, BartoszKamyszek commented on app/src/main/resources/application-dev.yml
> +    database: memory
tutaj to samo

2022-12-30 15:49 UTC, MCaberGIT approved these changes
OK

2022-12-30 16:04 UTC, BartoszKamyszek approved these changes

2022-12-30 16:06 UTC, merged