Feature/lesson8/task1 5
MaciekBella/invoicing-system-maciek-bella pull request #11
Opened 2022-12-30 17:53 UTC by MCaberGIT

2023-01-04 15:03 UTC, MaciekBella approved these changes

2023-01-04 15:56 UTC, BartoszKamyszek requested changes

2023-01-04 15:56 UTC, BartoszKamyszek commented on app/build.gradle
> +
po co ta linijka?

2023-01-04 15:56 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/config/SpringFoxConfiguration.java
> +  private ApiInfo apiInfo() {
api info jest nieużywane, sprawdzaliście jak to wygląda na stronce swaggera?

2023-01-04 15:56 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/config/SpringFoxConfiguration.java
> +        .build();
może jakiś kontakt jeszcze?

2023-01-04 15:56 UTC, BartoszKamyszek commented on app/src/main/resources/application.yml
> +Spring:
tu chyba z małej litery

2023-01-06 14:33 UTC, MaciekBella approved these changes

2023-01-06 14:44 UTC, BartoszKamyszek approved these changes

2023-01-06 14:49 UTC, merged