Lesson 9 Tax Calculator
MaciekBella/invoicing-system-maciek-bella pull request #12
Opened 2023-01-11 15:49 UTC by MaciekBella

2023-01-13 15:19 UTC, BartoszKamyszek commented
@MCaberGIT zrób review proszę, jeśli commit jest gotowy

2023-01-13 15:29 UTC, MCaberGIT approved these changes
Wygląda ok

2023-01-13 16:52 UTC, BartoszKamyszek requested changes

2023-01-13 16:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/DataBase.java
> +  }
ta metoda powinna być w serwisie, baza danych nie powinna wiedzieć o jej istnieniu

2023-01-13 16:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/controller/tax/TaxCalculatorApi.java
> +package pl.futurecollars.invoicing.controller.tax;
Jeśli masz pakiet o nazwie api to rozumiem, że powinno się to tam znaleźć dla zachowania konwencji

2023-01-13 16:52 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +public class TaxCalculatorService {
brakuje testów jednostkowych dla serwisu

2023-01-13 17:27 UTC, BartoszKamyszek requested changes

2023-01-13 17:27 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/db/InMemoryDataBase.java
> +  }
tak jak pisałem ta metoda powinna znaleźć się w warstwie serwisu a nie w bazie danych

2023-01-13 18:22 UTC, BartoszKamyszek requested changes
Dalej brakuje testów jednostkowych dla TaxCalculationService

2023-01-13 18:22 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
>    private final InMemoryDataBase inMemoryDataBase;
tym jaka baza jest używana powinny zarządzać profile, a nie bezpośrednie użycie implementacji. Wykorzystaj polimorfizm

2023-01-13 18:22 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  public BigDecimal visit(Predicate<Invoice> invoicePredicate, Function<InvoiceEntry, BigDecimal> invoiceEntryToValue) {
jeżeli metoda jest uzywana tylko w tej klasie to może być prywatna

2023-01-13 18:22 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/TaxCalculatorControllerTest.groovy
> +            }
formatowanie

2023-01-13 18:22 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/TaxCalculatorControllerTest.groovy
> +        def taxCalculatorResponse = taxCalculatorService.calculateTaxes("0")
Dlaczego testy nazywają się taxCalculatorControllerTest, a testujesz taxCalculatorService?

2023-01-13 18:22 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/TaxCalculatorControllerTest.groovy
> +        addInvoices(10)
Tworzysz 10 faktur, a tak naprawdę tylko jedna brana jest pod uwagę, zmień może albo dodaj metodę w TestHelpers tak abyś mogł definiować nip dla firmy na fakturze, wtedy stwórz sobie ze 2 faktury dla niej i zobacz czy wszystko wylicza się odpowiednio

2023-01-18 15:08 UTC, BartoszKamyszek requested changes

2023-01-18 15:08 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/tax/TaxCalculatorServiceTest.groovy
> +package pl.futurecollars.invoicing.controller.tax
popraw proszę pakiet

2023-01-18 15:08 UTC, BartoszKamyszek commented on app/src/main/java/pl/futurecollars/invoicing/service/TaxCalculatorService.java
> +  private final InMemoryDataBase inMemoryDataBase;
Tutaj nie chodziło o brak Autowired, ale o to, żebyś dał jako Typ Database

2023-01-18 15:08 UTC, BartoszKamyszek commented on app/src/test/groovy/pl/futurecollars/invoicing/controller/tax/TaxCalculatorServiceTest.groovy
> +@SpringBootTest
W testach jednostkowych nie powinniśmy uruchamiać kontekstu springa ani używać mockMvc, zamockuj bazę danych i sprawdź samo działanie serwisu, masz już przecież przykłady w swoim projekcie -> InvoiceServiceUnitTest

2023-01-20 18:44 UTC, BartoszKamyszek approved these changes

2023-01-21 14:52 UTC, merged