Feature/lesson11/tasks
MaciekBella/invoicing-system-maciek-bella pull request #13
Opened 2023-01-12 02:50 UTC by MCaberGIT

2023-01-12 11:28 UTC, BartoszKamyszek commented
Tutaj poproszę jeszcze screena z pgadmina z utworzoną bazą i tabelami przez flyway

2023-01-13 15:08 UTC, MaciekBella requested changes

2023-01-13 15:08 UTC, MaciekBella commented on app/src/main/resources/aplication-sql.yaml
> +  database: memory
Literówka w  nazwie pliku.

2023-01-13 15:15 UTC, MCaberGIT commented on app/src/main/resources/aplication-sql.yaml
> +  database: memory
poprawione

2023-01-13 15:21 UTC, BartoszKamyszek commented on app/src/main/resources/aplication-sql.yaml
> +  database: memory
jest jeszcze jedna literówka, plik musi się nazywać application a nie aplication, włączałeś aplikacje z tym profilem?

2023-01-13 15:30 UTC, MaciekBella submitted a review, later dismissed

2023-01-13 16:54 UTC, BartoszKamyszek commented
przed review przypominam się ze screenem z pgadmina, możesz go wrzucić tutaj jako komentarz

2023-01-18 00:41 UTC, MCaberGIT commented
> przed review przypominam się ze screenem z pgadmina, możesz go wrzucić tutaj jako komentarz
![ss Git Task 11](https://user-images.githubusercontent.com/111911691/213052841-75760021-d11f-4c74-8f18-f5a49edc9f65.png)

2023-01-19 23:08 UTC, BartoszKamyszek requested changes
Dodaj sobie do build.gradle baze h2, tak, żebyś nie musiał mieć fizycznego połączenia do bazy w testach. Problem nie jest z flyway, tylko z jdbc, dodaj coś takiego `    runtimeOnly 'com.h2database:h2:1.4.200'` i jeszcze najlepiej ustaw, żeby defaultowo aplikacja odpalała się z profilem dev i bez flyway, czyli dodaj do application.yaml `spring:
  profiles:
    active: dev
  flyway:
    enabled: false`

2023-01-20 17:44 UTC, BartoszKamyszek approved these changes

2023-01-20 17:47 UTC, merged