Feature/lesson14/tasks
MaciekBella/invoicing-system-maciek-bella pull request #16
Opened 2023-02-09 16:21 UTC by MaciekBella

2023-02-10 19:04 UTC, MaciekBella reviewed
![Zrzut ekranu_20230210_200132](https://user-images.githubusercontent.com/110846766/218176171-701833ca-7309-423c-8aea-c22e1ea99f3e.png)

2023-02-10 21:10 UTC, BartoszKamyszek requested changes

2023-02-10 21:10 UTC, BartoszKamyszek commented on .github/workflows/main.yml
> +        run:  chmod +x ./gradlew
usunąłeś słówko build i projekt się nie buduje, github actions nie puścił testów, a jeden na pewno failuje. Uruchomiłeś lokalnie te testy? Bo niemożliwe, że przeszły Ci wszystkie na zielono.

2023-02-10 21:10 UTC, BartoszKamyszek commented on app/build.gradle
> +                     'pl/futurecollars/invoicing/db/DatabaseConfigurator.class',
Jeżeli dodałeś już nową klasę z konfiguracją mongo to też ją tutaj dodaj

2023-02-10 21:10 UTC, BartoszKamyszek commented on app/src/main/resources/application-mongo.yml
> +Invoicing-system:
z małej litery

2023-02-13 13:16 UTC, BartoszKamyszek requested changes

2023-02-13 14:27 UTC, BartoszKamyszek approved these changes

2023-02-13 14:28 UTC, merged