Lesson7
MaciekBella/invoicing-system-maciek-bella pull request #9
Opened 2022-12-29 14:32 UTC by MCaberGIT

task 1
task 2
task 3
task 4
task 5

2022-12-29 15:32 UTC, MaciekBella approved these changes

2022-12-29 15:38 UTC, BartoszKamyszek requested changes
brakuje ekstrakcji wersji, tak jak w zadaniu: Cleanup the build.gradle file: extract versions to variables, unify the way you specify dependencies, remove unnecessary

2022-12-30 15:38 UTC, MaciekBella approved these changes

2022-12-30 16:05 UTC, BartoszKamyszek approved these changes

2022-12-30 16:06 UTC, merged